FROM python:3.10.11-slim

WORKDIR /app

# Project files
COPY requirements.txt .
COPY ./app .

# Project libraries
RUN apt update && apt install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0

# Setup a local user
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# Project dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Run 
ENV PATH="/home/appuser/.local/bin:$PATH"
CMD ["flask", "run", "-h", "0.0.0.0", "-p", "1234"]
